### ISSUE TITLE
safari error

### ISSUE THREAD

**Issue by viniciusdacal** [nicgirault/angular-trello-api-client#8]
When trying to use `get` method, I get this error in the console
undefined is not an object (evaluating 'TrelloClient.get("/member/me/boards").then')

![captura de tela 2016-02-11 as 09 25 40](https://cloud.githubusercontent.com/assets/2660570/12975315/c4573b90-d0a1-11e5-8730-179b075c3e62.png)

any thoughts?

**Comment by nicgirault** [comment]
Thank you for reporting this bug @viniciusdacal. I was not returning a promise when the $http promise is rejected.
